[package]
name = "wasmcloud-test-util"
version = "0.1.3"
edition = "2018"
authors = [ "wasmcloud Team" ]
license = "Apache-2.0"
description = "Test tools and utilities for wasmcloud"
homepage = "https://github.com/wasmcloud/wasmcloud"
repository = "https://github.com/wasmcloud/wasmcloud-test"
readme = "README.md"

[dependencies]
wasmcloud-interface-testing = "0.1"
wasmbus-rpc = "0.3"
regex = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
base64 = "0.13"
log = "0.4"
serde = { version = "1.0", features=["derive"]}
serde_json = "1.0"
termion = "1.5"
tokio = { version = "1", features = ["full"]}
toml = "0.5"
wascap = "0.6"

