[package]
name = "wasmcloud-test-util"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
base64 = "0.13"
log = "0.4"
ratsio = "0.4.0-alpha.1"
serde = { version = "1.0", features=["derive"]}
serde_json = "1.0"
termion = "1.5"
tokio = { version = "1", features = ["full"]}
toml = "0.5"
wascap = "0.6"

[dependencies.wasmbus-rpc]
version = "0.3"
#path = "../../weld/rpc-rs"


